[package]
name = "presentation"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.7.3", features = ["csr"] }
stylance = "0.5.3"
shell = { path = "../shell" }

[package.metadata.stylance]
output_file= "./styles/bundle.css"
output_dir = "./styles"
